#116: add variables to resolver data
isographlabs/isograph pull request #120
Opened 2024-09-24 20:21 UTC by ch1ffa

Closes #116

This PR exposes `variables` field to `EagerReaderArtifact` and `ComponentReaderArtifact` resolvers. 

It has been temporarily added as `Variables` type. In the next PR it should be replaced by generated type.

2024-09-24 20:23 UTC, ch1ffa commented on libs/isograph-react/src/core/reader.ts
> +export type ResolverData<
not sure about this type name

2024-09-25 00:33 UTC, rbalicki2 commented on libs/isograph-react/src/core/reader.ts
> +export type ResolverData<
`ResolverFirstParameter`?

2024-09-25 00:52 UTC, rbalicki2 requested changes
Just a few minor changes and then this looks g2g!! I'm super excited about this. I wasn't expecting that `Variables` would be part of the `param_type`, but that's certainly the correct move. Awesome!

2024-09-25 00:52 UTC, rbalicki2 commented on crates/graphql_artifact_generation/src/eager_reader_artifact.rs
> +    // TODO: import generated variable types
Nit: Change `0` to `1` above so that the indentation is correct

2024-09-25 00:52 UTC, rbalicki2 commented on crates/graphql_artifact_generation/src/eager_reader_artifact.rs
> +        export type {reader_param_type} = {{\n\
Let's fix the indentation here by adding `{indent}` where `let indent = "  "`

2024-09-25 00:52 UTC, rbalicki2 commented on libs/isograph-react/src/core/reader.ts
> +  readonly variables: TVariables | null;
I just pushed a commit that makes `variables` non-null in `FragmentReference`, so no need to make it null here

2024-09-25 03:54 UTC, rbalicki2 commented
Sorry for the last minute change. Let's not name it `variables`. Variables are global in GraphQL, which will confuse users.

Let's instead call it either `arguments` or `parameters`. `arguments` I think would be suboptimal, because one cannot name a variable arguments because JavaScript is really silly.

So, by process of elimination, let's name this field `parameters`. Thoughts?

2024-09-25 08:10 UTC, closed without merging

2024-09-25 08:14 UTC, ch1ffa commented
Sorry, I'll make a new one, accidentally created PR from the main branch and it's a pain to rebase onto new commits