add Apache 2.0 and MIT License to the repository
isographlabs/isograph pull request #2
Opened 2023-11-02 15:40 UTC by saminoorsyed

Hey there,

      I know this likely won't be added yet, but I thought putting in the Licensing info might be a good step to getting other contributors to work on this project. I wasn't sure who to put as the copyright holder for the MIT License, so I put Robert Balicki. I'll get in touch with Rob about contributing in a more directed way this next week.

--Sami

2023-12-10 15:39 UTC, saminoorsyed commented
Merge conflicts: resolved by defaulting to main and adding licensing info

2023-12-11 04:46 UTC, rbalicki2 requested changes
Just one nit re: the base Cargo toml, and then we're good to go!!! Thanks for adding this.

2023-12-11 04:46 UTC, rbalicki2 commented on Cargo.toml
> +license = "MIT"
TIL — cargo toml's that define workspaces but not packages (as this one does) don't support the license key.

if you try to compile the project like this, it complains about 

```
error: failed to parse manifest at `/Users/rbalicki/code/isograph/Cargo.toml`

Caused by:
  missing field `name`
  in `package`
```

Can you revert this file change, and then this is good to go and we'll merge it!!!

2023-12-11 14:50 UTC, saminoorsyed commented
done!

2023-12-13 17:45 UTC, rbalicki2 approved these changes
Awesome, thanks for making these changes!

2023-12-13 17:45 UTC, merged