Generate pointers for subtypes on supertypes
isographlabs/isograph pull request #227
Opened 2024-10-28 19:51 UTC by PatrykWalach

Part of #53

2024-10-28 20:21 UTC, PatrykWalach commented on crates/isograph_schema/src/add_pointers_to_supertypes.rs
> +                variant: crate::ClientFieldVariant::ImperativelyLoadedField(
We can replace this after merging #228, then we can validate in #229

2024-10-29 18:24 UTC, rbalicki2 requested changes
LGTM, just a few nits, then let's get this landed.

We can land this, even if selecting these fields will create invalid queries.

2024-10-29 18:24 UTC, rbalicki2 commented on crates/isograph_schema/src/add_pointers_to_supertypes.rs
> +                        crate::FieldType::ServerField(next_server_field_id),
nit: we should import `FieldType` (i.e. replace qualified path with use via rust analyzer)

2024-10-29 18:24 UTC, rbalicki2 commented on crates/isograph_schema/src/add_pointers_to_supertypes.rs
> +                        ProcessTypeDefinitionError::FieldExistsOnSubtype {
Let's rename `FieldExistsOnSubtype` since we are creating a field on the supertype

2024-10-29 18:24 UTC, rbalicki2 commented on crates/isograph_schema/src/add_pointers_to_supertypes.rs
> +                    common_lang_types::WithSpan {
also here, let's import `WithSpan`

2024-10-29 18:24 UTC, rbalicki2 commented on crates/isograph_schema/src/add_pointers_to_supertypes.rs
> +                        field_name.into(),
we probably don't need `.into` here

2024-10-29 19:09 UTC, merged