process client pointer
isographlabs/isograph pull request #254
Opened 2024-11-06 20:57 UTC by PatrykWalach

2024-11-12 02:01 UTC, rbalicki2 requested changes
amazing work!!! so far just superficial changes. Love what I see.

2024-11-12 02:01 UTC, rbalicki2 commented on crates/isograph_schema/src/process_client_field_declaration.rs
> +    fn add_client_pointer_to_object(
note to self to continue from here

2024-11-12 03:57 UTC, rbalicki2 reviewed
Okay, finished my review. Amazing work!!

2024-11-13 23:38 UTC, rbalicki2 requested changes

2024-11-13 23:38 UTC, rbalicki2 commented on crates/isograph_schema/src/isograph_schema.rs
> +                                                   This is indicative of a bug in Isograph."
weird tabbing

2024-11-13 23:38 UTC, rbalicki2 commented on crates/isograph_schema/src/isograph_schema.rs
> +    // TODO this should probably be a HashMap
this comment is outdated as well

2024-11-13 23:38 UTC, rbalicki2 commented on crates/isograph_schema/src/process_client_field_declaration.rs
> +        let to_object = &self.server_field_data.server_objects[to_object_id.inner().as_usize()];
```
        let to_object = self.server_field_data.object(*to_object_id.inner());
        let parent_object = self.server_field_data.object(parent_object_id);
```
        
let's also rename `object` to `parent_object`

2024-11-13 23:38 UTC, rbalicki2 commented on crates/isograph_schema/src/process_client_field_declaration.rs
> +        let object = &mut self.server_field_data.server_objects[parent_object_id.as_usize()];
`.object_mut`

2024-11-13 23:38 UTC, rbalicki2 commented on crates/isograph_schema/src/isograph_schema.rs
> +    pub to: GraphQLTypeAnnotation<ServerObjectId>,
`TypeAnnotation<ServerObjectId>`

2025-01-20 01:28 UTC, rbalicki2 requested changes
LGTM, just a few nits and other comments, but the gist (process client pointer) lgtm and this should be landable with no substantive changes

2025-01-20 01:28 UTC, rbalicki2 commented on crates/isograph_schema/src/isograph_schema.rs
> +    pub condition_selection_set: Vec<
nit: this might be better named as a `reader_selection_set`? Thoughts?

2025-01-20 01:28 UTC, rbalicki2 commented on crates/isograph_schema/src/process_client_field_declaration.rs
> +                        ProcessClientFieldDeclarationError::TypePointedToHasNoId {
nit: `ClientFieldTargetTypeHasNoId` and `target_type_name`?

2025-01-20 01:28 UTC, rbalicki2 commented on crates/isograph_schema/src/isograph_schema.rs
>          match &self.client_fields[client_field_id.as_usize()] {
nit: `schema.client_fields` should now be `schema.client_types`, which can be in a separate PR or in the same

2025-01-20 01:28 UTC, rbalicki2 commented on crates/isograph_schema/src/process_client_field_declaration.rs
> +    #[error("Invalid type pointed to. `{to_type_name}` is a scalar. You are attempting to define a pointer on it. \
invalid client pointer target type

2025-01-20 01:28 UTC, rbalicki2 commented on crates/isograph_schema/src/validate_client_field.rs
>          get_all_errors_or_all_ok_as_hashmap(client_fields.iter().map(|unvalidated_client| {
nit: `unvalidated_client_type`

2025-01-20 01:28 UTC, rbalicki2 commented on crates/isograph_schema/src/validate_client_field.rs
> +            ClientType::ClientPointer(_) => todo!(),
maybe something like `todo!("validating client pointer selection sets is not implemented yet")` or something?

But also, in this case, would it work if we call `validate_client_field_selection_set`?

2025-01-20 01:28 UTC, rbalicki2 commented on crates/isograph_schema/src/validate_client_field.rs
>                  validate_client_field(
I wonder if we can make client pointers and fields both implement the same interface, and have `validate_client_field` accept an `&impl ThatCommonInterface`, since presumably the validation is identical

But we could also duplicate it, if it's simple

Anyway, let's have `todo!("validating client pointers is not yet implemented")`

2025-01-20 01:28 UTC, rbalicki2 commented on crates/isograph_lang_parser/src/parse_iso_literal.rs
> +            to_type: GraphQLTypeAnnotation::Named(GraphQLNamedTypeAnnotation(parent_type)),
I think we need to parse the literal `to` and then a type annotation, and that type annotation becomes the `to_type`, right?

could be separate PR, but if so, leave a comment

2025-01-20 01:28 UTC, rbalicki2 commented on crates/isograph_lang_parser/src/parse_iso_literal.rs
>              parent_type,
let's add `parse_directives` above. Otherwise, you get `selection sets are required` if you accidentally add a directive. Anyway, directives will be eventually supported so for now, we should either parse them and throw if they're present (most preferred) or silently ignore them (least preferred) or add them as an unused field on client pointer

could be separate PR

2025-01-26 16:33 UTC, PatrykWalach commented on crates/isograph_lang_parser/src/parse_iso_literal.rs
> +            to_type: GraphQLTypeAnnotation::Named(GraphQLNamedTypeAnnotation(parent_type)),
I'll do this in separate PR

2025-01-26 16:34 UTC, rbalicki2 commented on crates/isograph_lang_parser/src/parse_iso_literal.rs
> +            to_type: GraphQLTypeAnnotation::Named(GraphQLNamedTypeAnnotation(parent_type)),
sgtm

2025-01-26 16:41 UTC, PatrykWalach commented on crates/isograph_schema/src/isograph_schema.rs
>          match &self.client_fields[client_field_id.as_usize()] {
I'll also do this in separate PR, this PR should be ready after tests pass

2025-01-30 23:14 UTC, rbalicki2 approved these changes
lets gooo

2025-01-30 23:19 UTC, merged