no_babel_transform option & change entrypoint iso overloads to return void
isographlabs/isograph pull request #286
Opened 2024-11-27 20:05 UTC by PatrykWalach

2024-12-21 16:16 UTC, rbalicki2 commented on crates/graphql_artifact_generation/src/iso_overload_file.rs
> +export function iso<T>(
great catch

2024-12-21 16:36 UTC, rbalicki2 reviewed
This makes me think that we should not be using error|ignore|warning for this, but instead have a `"no_babel_transform": bool` option or something. Thoughts?

Anyway, happy to land this as is to unblock Randall, but if you're up for making ☝️ change, we can skip a step

2024-12-21 16:39 UTC, PatrykWalach commented
Makes sense, I can make this change

2024-12-26 04:29 UTC, rbalicki2 requested changes
Looks great to me, thanks for identifying this and getting it done. Just a few nits

2024-12-26 04:29 UTC, rbalicki2 commented on crates/isograph_config/src/compilation_options.rs
> +        no_babel_transform: options.no_babel_transform,
Let's rebase this on main and regenerate the schema as well

2024-12-26 04:29 UTC, rbalicki2 commented on crates/graphql_artifact_generation/src/iso_overload_file.rs
> -  return (clientFieldResolver: any) => clientFieldResolver;"
can we modify this error message too? E.g. add "If you cannot use the babel transform, set `options.no_babel_transform` to `true` in your Isograph config."

2024-12-28 08:36 UTC, rbalicki2 approved these changes
LGTM shipittt

2024-12-28 08:38 UTC, merged